### ISSUE TITLE
quickstart has multiple errors

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh-notebooks#23]
- [ ] references `apps/movies.html` (404), should be `apps/movies`
- [ ] ocean demo is down (do we even support downsampling?)
- [ ] jsfiddle references bokeh 0.8.0 (!)

**Comment by bryevdv** [comment]
@mattpap we support making an app that does downsampling, there is nothing built in. I'd like to re-write the ocean demo as a new Bokeh app I just have not had the time yet. I'd also like to migrate the JS examples to codepen since deploys there could be automated, but there is no point until the BokehJS API is updated.

**Comment by bryevdv** [comment]
done at some point
