### ISSUE TITLE
remote_ocean_slider example is missing

### ISSUE THREAD

**Issue by thoth291** [bokeh/bokeh-notebooks#24]
Hi,

I'm looking for how implement something very close to Downsampling example here https://github.com/bokeh/bokeh-notebooks/blob/master/quickstart/quickstart.ipynb
Is it right that Downsampling was replaced by Datashader?
Any comments gentlemen: @jbednar , @pzwang ?

If it's so - then obviously this example needs to be re-implemented using Datashader or something similar to it...

What I'm trying to do is to visualize a big cube of data sitting on remote machine. And I need to QC it in all directions (XY, XZ, YZ). Obviously number of points per slice are few billions, but resolution on the client will be quite small so all the data is not needed.
I thought that bokeh has a perfect solution and was very happy when I've found this example - but, unfortunately, I couldn't find it's implementation or any other details and Datashader module looks like more designed for scatter plots rather than images.

Please help.

Sincerely, 
Thoth.

**Comment by jbednar** [comment]
Please bear in mind that both Bokeh and datashader are open-source projects, not something you've paid for. :-)   So it's ok to ask for something, but not to demand it!  And also remember that they are separate projects; datashader is managed independently of bokeh, though we do try to make them work well together.  

In any case, Bokeh allows you to implement downsampling in any form that you like, via the bokeh server that can read the data, subsample it arbitrarily, and then pass it to the browser.  Datashader is one example of how to do that, but it's a new project, and we've only worked on some glyph types (point-line objects (scatterplots) and line segments) so far.  Full support for rasters and dense cubes is planned but not yet scheduled on our list of immediate tasks.

That said, Datashader should already work well for gridded data if you view it from a distance, as you seem to suggest here; as long as there are at least a couple of datapoints per pixel, it should be effectively rasterized anyway.  What we plan to add is area-filling support so that it can continue to look like a raster once zooming in further, but that's more to avoid confusion than a required feature, since the current approach also has its advantages (i.e. clearly showing each sample location).

**Comment by thoth291** [comment]
I'm sorry that it sounded as demanding new features. I was basically asking if my understanding of things were right or not... (Though, I personally don't mind to pay for some features to come up faster than others ;-) ).

Thank you for clarification!
I will basically implement my own downsampling of the data using native bokeh features.

I wonder if there are any list of scheduled/planned tasks publicly available.
That would be great if users could vote for some of the features and plan their dependency on your project based on your roadmap.

Thanks again!

**Comment by jbednar** [comment]
Yes, I hope to put up a roadmap of planned features this week, after discussing with the rest of the team.

**Comment by bryevdv** [comment]
closing, data shader materials in this repo will be pared down considerably. We will provide some motivational examples and perhaps one exercise, but then provide links to official datashader project resources for further materials.
