### ISSUE TITLE
Environment Dependencies

### ISSUE THREAD

**Issue by ChaosCom** [bokeh/bokeh-notebooks#96]
Hello,

I have a question about the dependencies listed in environment.yml : 
What is the rationale behind the following dependencies:
- firefox
- selenium
- geckodriver

Especially the firefox dependency is pretty heavy, and I was wondering what that is a requirement in the first place.
Thank you for your answers in advance.

**Comment by mattpap** [comment]
No, it's just needed in https://github.com/bokeh/bokeh-notebooks/blob/main/tutorial/10%20-%20Exporting%20and%20Embedding.ipynb. Only selenium is really required.

**Comment by ChaosCom** [comment]
Allright, thanks for the pointers. 
I've successfully uninstalled the firefox dependency with (seemingly, for now) no detrimental side-effects.

**Comment by bryevdv** [comment]
I guess I should also clarify, I thought this was asking about the env file in the main repo. The one here has all those dependencies because that's what is necessary to run *all* the notebooks (the only reasonable env to define by default). But if you don't care about the image export ones then you can skip those dependencies.
